# Generated by Django 4.2.20 on 2025-05-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_matchresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_mountains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_rural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='more_than_3_bedrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='near_beach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
