# Generated by Django 4.2.20 on 2025-05-17 07:09

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_has_pool_profile_in_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to='house_images/', validators=[profiles.models.ImageValidator(max_size_mb=2)]),
        ),
    ]
