# Generated by Django 4.2.20 on 2025-05-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_houseimage_is_main_alter_houseimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimage',
            name='is_main',
        ),
    ]
