# Generated by Django 4.2.20 on 2025-09-15 12:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
