# Generated by Django 4.2.20 on 2025-05-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
